server:
  port: ${PORT:2333}

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:youshallnotpass}

    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false

  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"

plugins:
  youtube:
    enabled: true

    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

    oauth:
      enabled: false

    clients:
      - WEB
      - MWEB

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: INFO

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""
