server:
  port: ${PORT:2333}

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"

  server:
    password: ${LAVALINK_PASSWORD:youshallnotpass}

    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false

plugins:
  youtube:
    enabled: true

    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

    clients:
      - WEB
      - MWEB
      - TVHTML5_SIMPLY_EMBEDDED_PLAYER

    cookies:
      file: cookies.txt

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: INFO

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

server:
  error:
    include-message: always
